services:  
  api:    
    build:
      dockerfile: Dockerfile
    container_name: api_backend   
    restart: "always" 
    ports:      
      - '4000:4000'  
      - '3000:3000'  
    volumes:
      - ./:/app